from typing import Iterable,Optional

def root_project()->str: ...
def absolute_path(relative_path:str,root:str=root_project())->str: ...
def partes_de_linea(linea:str, delimiter:str=",")-> list[str]: ...
def iterable_de_fichero(file:str,encoding:str='utf-8') -> Iterable[str]: ...    
def lineas_de_fichero(file:str,encoding:str='utf-8') -> list[str]: ...
def lineas_de_csv(file:str, delimiter:str=",", encoding:str='utf-8')-> list[list[str]]: ...
def iterable_de_csv(file:str, delimiter:str=",", encoding:str='utf-8')-> Iterable[list[str]]: ...
def iterable_de_csv_partes(file:str, delimiter:str=",", encoding='utf-8')-> Iterable[str]: ... 
def dict_de_csv(file:str, delimiter:str=",", encoding:str='utf-8')-> dict[str,list[str]]: ...        
def read(file:str,encoding:str='utf-8') -> str: ...  
def write(file:str,texto:str) -> None: ...
def write_iterable(file:str,iterable:Iterable[str], encoding='utf-8') -> None: ...
def encoding(file:str)->Optional[str]: ...