from typing import TypeVar, Optional

E = TypeVar('E')

def optional_get(e:Optional[E])->E: ...
def optional_is_empty(e:Optional[E])->bool: ...
def optional_is_present(e:Optional[E])->bool: ...
def optional_get_or_else(e:Optional[E], other:E)->E:...
