from typing import TypeVar, Callable

E = TypeVar('E')
K = TypeVar('K')

def transform(inText:str,reglas:dict[str,str]) -> str:...
def to_unicode(r:str) -> str: ...
def strip_non_ascii(string):...
def str_split(text:str,sep:str=',') -> list[str]:...
def strplist(text:str,value:Callable[[str],E])->list[E]:...
def strpset(text:str,value:Callable[[str],E])->set[E]:...
def strpdict(text:str,key:Callable[[str],K],value:Callable[[str],E])->dict[K,E]:...